# Jekyll site config (only the important lines shown)
title: FlightLine — Memphis DC
email: msrja9@gmail.com
description: "Every ZIP = Runway. Every Scan = Proof. Every Payment = Public."
url: "https://taylor7617.github.io"        # your GitHub Pages root
baseurl: "/flightline-memphisdc"           # MUST match repo name
theme: minima
plugins:
  - jekyll-feed
