name: "🐞 Bug"
description: "Report an issue"
labels:
  - bug
  - needs-triage
body:
  - type: textarea
    id: what
    attributes:
      label: "What happened?"
      description: "Clear, reproducible steps"
      placeholder: |
        1) …
        2) …
        3) …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "What did you expect to happen?"

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Browser/OS and page path or URL (if relevant)"

  - type: input
    id: url
    attributes:
      label: "Page URL (if any)"
