name: "🐞 Bug"
description: "Report an issue"
title: "[Bug]: "
labels:
  - bug
  - needs-triage
body:
  - type: textarea
    id: repro
    attributes:
      label: "Steps to reproduce"
      description: "Use generic devices/browsers; only name specific models if relevant."
      placeholder: |
        1) Open /gates/ on a small screen (≤ 768px width) — e.g., iOS Safari or Android Chrome
        2) Scroll to the top of the page
        3) Observe the CTA bar area
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected result"
      placeholder: "CTA bar visible under the nav on all viewports"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual result"
      placeholder: "Blank space where CTA bar should be. Reproduces on iOS Safari 17 and Android Chrome 128."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "S1 – Critical (no workaround)"
        - "S2 – High (major impact)"
        - "S3 – Medium (minor impact)"
        - "S4 – Low (cosmetic)"
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: "Platforms affected"
      options:
        - label: "iOS"
        - label: "Android"
        - label: "Desktop"
        - label: "Tablet"

  - type: input
    id: pages
    attributes:
      label: "Page path(s)"
      placeholder: "/gates/, /about/"

  - type: textarea
    id: env
    attributes:
      label: "Environment details"
      description: "Browser + OS versions"
      placeholder: "iOS 17.5 / Safari 17; Android 14 / Chrome 128; macOS 14.5 / Chrome 128"

  - type: textarea
    id: notes
    attributes:
      label: "Notes / Screenshots"
      description: "Drag images here to attach."
