name: "Bug"
description: "Report an issue"
title: "[Bug]: "
labels:
  - bug
  - needs-triage
body:
  - type: textarea
    id: repro
    attributes:
      label: "Steps to reproduce"
      placeholder: |
        1) Action
        2) Action
        3) Result
    validations:
      required: true
