title: "FlightLine — Memphis DC"
description: "Capital of NetTopia — public runway"
theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag
exclude:
  - node_modules
  - vendor
  - .github
  - README.md
  - Repo Structure
